---
abstract: 'determine whether strict (but slow) tests should be enabled'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-StrictMode
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Devel::StrictMode:
    file: lib/Devel/StrictMode.pm
    version: 0.001
requires:
  perl: 5.006
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Devel-StrictMode/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Devel-StrictMode
  homepage: https://metacpan.org/release/Devel-StrictMode
  license: http://dev.perl.org/licenses/
version: 0.001
